os:
  - linux
  - osx

after_success: npm run coverage

language: node_js
node_js:
  - 'node'
  - '6'
  - '4'
  
sudo: required
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - libavahi-compat-libdnssd-dev
    # - libnss-mdns
    # - libssp-dev
    # - ubuntu-toolchain-r-test
    # packages:
    # - g++-5
# env:
#   - CXX=g++-5
